// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user/user.proto

//服务名

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserService service

type UserService interface {
	List(ctx context.Context, in *PageDto, opts ...client.CallOption) (*PageDto, error)
	Login(ctx context.Context, in *User, opts ...client.CallOption) (*User, error)
	Logout(ctx context.Context, in *User, opts ...client.CallOption) (*User, error)
	Save(ctx context.Context, in *User, opts ...client.CallOption) (*User, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) List(ctx context.Context, in *PageDto, opts ...client.CallOption) (*PageDto, error) {
	req := c.c.NewRequest(c.name, "UserService.list", in)
	out := new(PageDto)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Login(ctx context.Context, in *User, opts ...client.CallOption) (*User, error) {
	req := c.c.NewRequest(c.name, "UserService.login", in)
	out := new(User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Logout(ctx context.Context, in *User, opts ...client.CallOption) (*User, error) {
	req := c.c.NewRequest(c.name, "UserService.logout", in)
	out := new(User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Save(ctx context.Context, in *User, opts ...client.CallOption) (*User, error) {
	req := c.c.NewRequest(c.name, "UserService.save", in)
	out := new(User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	List(context.Context, *PageDto, *PageDto) error
	Login(context.Context, *User, *User) error
	Logout(context.Context, *User, *User) error
	Save(context.Context, *User, *User) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		List(ctx context.Context, in *PageDto, out *PageDto) error
		Login(ctx context.Context, in *User, out *User) error
		Logout(ctx context.Context, in *User, out *User) error
		Save(ctx context.Context, in *User, out *User) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) List(ctx context.Context, in *PageDto, out *PageDto) error {
	return h.UserServiceHandler.List(ctx, in, out)
}

func (h *userServiceHandler) Login(ctx context.Context, in *User, out *User) error {
	return h.UserServiceHandler.Login(ctx, in, out)
}

func (h *userServiceHandler) Logout(ctx context.Context, in *User, out *User) error {
	return h.UserServiceHandler.Logout(ctx, in, out)
}

func (h *userServiceHandler) Save(ctx context.Context, in *User, out *User) error {
	return h.UserServiceHandler.Save(ctx, in, out)
}
