version: "3"
services:
  mysql:
    image: mysql:5.7.32
    ports:
    - "33600:3360"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
  redis:
    image: redis
    ports:
    - "6379:6379"
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#  consul:
#    image: consul
#    ports:
#    - "8300:8300"
#    - "8301:8301"
#    - "8302:8302"
#    - "8500:8500"
#    - "8600:8600"
  jaeger:
    image: jaegertracing/all-in-one
    ports:
    - "6831:6831/udp"
    - "16686:16686"
