// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: course/user-srv/proto/dto/user.proto

package dto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UserDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LoginName string `protobuf:"bytes,3,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	Password  string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *UserDto) Reset() {
	*x = UserDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_course_user_srv_proto_dto_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDto) ProtoMessage() {}

func (x *UserDto) ProtoReflect() protoreflect.Message {
	mi := &file_course_user_srv_proto_dto_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDto.ProtoReflect.Descriptor instead.
func (*UserDto) Descriptor() ([]byte, []int) {
	return file_course_user_srv_proto_dto_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserDto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserDto) GetLoginName() string {
	if x != nil {
		return x.LoginName
	}
	return ""
}

func (x *UserDto) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PageDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize int64      `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNum  int64      `protobuf:"varint,2,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	SortBy   string     `protobuf:"bytes,3,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	Asc      bool       `protobuf:"varint,4,opt,name=asc,proto3" json:"asc,omitempty"`
	Users    []*UserDto `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *PageDto) Reset() {
	*x = PageDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_course_user_srv_proto_dto_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageDto) ProtoMessage() {}

func (x *PageDto) ProtoReflect() protoreflect.Message {
	mi := &file_course_user_srv_proto_dto_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageDto.ProtoReflect.Descriptor instead.
func (*PageDto) Descriptor() ([]byte, []int) {
	return file_course_user_srv_proto_dto_user_proto_rawDescGZIP(), []int{1}
}

func (x *PageDto) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageDto) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *PageDto) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *PageDto) GetAsc() bool {
	if x != nil {
		return x.Asc
	}
	return false
}

func (x *PageDto) GetUsers() []*UserDto {
	if x != nil {
		return x.Users
	}
	return nil
}

type LoginUserDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LoginName string `protobuf:"bytes,2,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Token     string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LoginUserDto) Reset() {
	*x = LoginUserDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_course_user_srv_proto_dto_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginUserDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserDto) ProtoMessage() {}

func (x *LoginUserDto) ProtoReflect() protoreflect.Message {
	mi := &file_course_user_srv_proto_dto_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserDto.ProtoReflect.Descriptor instead.
func (*LoginUserDto) Descriptor() ([]byte, []int) {
	return file_course_user_srv_proto_dto_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginUserDto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoginUserDto) GetLoginName() string {
	if x != nil {
		return x.LoginName
	}
	return ""
}

func (x *LoginUserDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginUserDto) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UpdatePass struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldPass string `protobuf:"bytes,1,opt,name=oldPass,proto3" json:"oldPass,omitempty"`
	NewPass string `protobuf:"bytes,2,opt,name=newPass,proto3" json:"newPass,omitempty"`
	UserId  string `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *UpdatePass) Reset() {
	*x = UpdatePass{}
	if protoimpl.UnsafeEnabled {
		mi := &file_course_user_srv_proto_dto_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePass) ProtoMessage() {}

func (x *UpdatePass) ProtoReflect() protoreflect.Message {
	mi := &file_course_user_srv_proto_dto_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePass.ProtoReflect.Descriptor instead.
func (*UpdatePass) Descriptor() ([]byte, []int) {
	return file_course_user_srv_proto_dto_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePass) GetOldPass() string {
	if x != nil {
		return x.OldPass
	}
	return ""
}

func (x *UpdatePass) GetNewPass() string {
	if x != nil {
		return x.NewPass
	}
	return ""
}

func (x *UpdatePass) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_course_user_srv_proto_dto_user_proto protoreflect.FileDescriptor

var file_course_user_srv_proto_dto_user_proto_rawDesc = []byte{
	0x0a, 0x24, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x73, 0x72,
	0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x68, 0x0a, 0x07,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x8e, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x67, 0x65, 0x44,
	0x74, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x72, 0x74,
	0x42, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x72, 0x74, 0x42, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x61,
	0x73, 0x63, 0x12, 0x23, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x74, 0x6f,
	0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x67, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x58, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x6c, 0x64, 0x50, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x6c, 0x64, 0x50, 0x61, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x50,
	0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x50, 0x61,
	0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42, 0x1b, 0x5a, 0x19, 0x63, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x73, 0x72, 0x76, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_course_user_srv_proto_dto_user_proto_rawDescOnce sync.Once
	file_course_user_srv_proto_dto_user_proto_rawDescData = file_course_user_srv_proto_dto_user_proto_rawDesc
)

func file_course_user_srv_proto_dto_user_proto_rawDescGZIP() []byte {
	file_course_user_srv_proto_dto_user_proto_rawDescOnce.Do(func() {
		file_course_user_srv_proto_dto_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_course_user_srv_proto_dto_user_proto_rawDescData)
	})
	return file_course_user_srv_proto_dto_user_proto_rawDescData
}

var file_course_user_srv_proto_dto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_course_user_srv_proto_dto_user_proto_goTypes = []interface{}{
	(*UserDto)(nil),      // 0: user.UserDto
	(*PageDto)(nil),      // 1: user.PageDto
	(*LoginUserDto)(nil), // 2: user.LoginUserDto
	(*UpdatePass)(nil),   // 3: user.UpdatePass
}
var file_course_user_srv_proto_dto_user_proto_depIdxs = []int32{
	0, // 0: user.PageDto.users:type_name -> user.UserDto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_course_user_srv_proto_dto_user_proto_init() }
func file_course_user_srv_proto_dto_user_proto_init() {
	if File_course_user_srv_proto_dto_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_course_user_srv_proto_dto_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_course_user_srv_proto_dto_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_course_user_srv_proto_dto_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginUserDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_course_user_srv_proto_dto_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePass); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_course_user_srv_proto_dto_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_course_user_srv_proto_dto_user_proto_goTypes,
		DependencyIndexes: file_course_user_srv_proto_dto_user_proto_depIdxs,
		MessageInfos:      file_course_user_srv_proto_dto_user_proto_msgTypes,
	}.Build()
	File_course_user_srv_proto_dto_user_proto = out.File
	file_course_user_srv_proto_dto_user_proto_rawDesc = nil
	file_course_user_srv_proto_dto_user_proto_goTypes = nil
	file_course_user_srv_proto_dto_user_proto_depIdxs = nil
}
