// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gitee.com/jingshanccc/course/user/proto/dto/member.proto

package dto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MemberRegisterDto struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	LoginName            string   `protobuf:"bytes,5,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberRegisterDto) Reset()         { *m = MemberRegisterDto{} }
func (m *MemberRegisterDto) String() string { return proto.CompactTextString(m) }
func (*MemberRegisterDto) ProtoMessage()    {}
func (*MemberRegisterDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_342aa27b51529c11, []int{0}
}

func (m *MemberRegisterDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberRegisterDto.Unmarshal(m, b)
}
func (m *MemberRegisterDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberRegisterDto.Marshal(b, m, deterministic)
}
func (m *MemberRegisterDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberRegisterDto.Merge(m, src)
}
func (m *MemberRegisterDto) XXX_Size() int {
	return xxx_messageInfo_MemberRegisterDto.Size(m)
}
func (m *MemberRegisterDto) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberRegisterDto.DiscardUnknown(m)
}

var xxx_messageInfo_MemberRegisterDto proto.InternalMessageInfo

func (m *MemberRegisterDto) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *MemberRegisterDto) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *MemberRegisterDto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MemberRegisterDto) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *MemberRegisterDto) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

type MemberDto struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Sex                  string   `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Photo                string   `protobuf:"bytes,5,opt,name=photo,proto3" json:"photo,omitempty"`
	Integral             uint32   `protobuf:"varint,6,opt,name=integral,proto3" json:"integral,omitempty"`
	LearningTime         uint32   `protobuf:"varint,7,opt,name=learning_time,json=learningTime,proto3" json:"learning_time,omitempty"`
	RegisterTime         string   `protobuf:"bytes,8,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	LoginName            string   `protobuf:"bytes,9,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	CreateTime           string   `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Creator              string   `protobuf:"bytes,12,opt,name=creator,proto3" json:"creator,omitempty"`
	Updater              string   `protobuf:"bytes,13,opt,name=updater,proto3" json:"updater,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberDto) Reset()         { *m = MemberDto{} }
func (m *MemberDto) String() string { return proto.CompactTextString(m) }
func (*MemberDto) ProtoMessage()    {}
func (*MemberDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_342aa27b51529c11, []int{1}
}

func (m *MemberDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberDto.Unmarshal(m, b)
}
func (m *MemberDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberDto.Marshal(b, m, deterministic)
}
func (m *MemberDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberDto.Merge(m, src)
}
func (m *MemberDto) XXX_Size() int {
	return xxx_messageInfo_MemberDto.Size(m)
}
func (m *MemberDto) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberDto.DiscardUnknown(m)
}

var xxx_messageInfo_MemberDto proto.InternalMessageInfo

func (m *MemberDto) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MemberDto) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *MemberDto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MemberDto) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *MemberDto) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *MemberDto) GetIntegral() uint32 {
	if m != nil {
		return m.Integral
	}
	return 0
}

func (m *MemberDto) GetLearningTime() uint32 {
	if m != nil {
		return m.LearningTime
	}
	return 0
}

func (m *MemberDto) GetRegisterTime() string {
	if m != nil {
		return m.RegisterTime
	}
	return ""
}

func (m *MemberDto) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *MemberDto) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *MemberDto) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *MemberDto) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MemberDto) GetUpdater() string {
	if m != nil {
		return m.Updater
	}
	return ""
}

func init() {
	proto.RegisterType((*MemberRegisterDto)(nil), "user.MemberRegisterDto")
	proto.RegisterType((*MemberDto)(nil), "user.MemberDto")
}

func init() {
	proto.RegisterFile("gitee.com/jingshanccc/course/user/proto/dto/member.proto", fileDescriptor_342aa27b51529c11)
}

var fileDescriptor_342aa27b51529c11 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbd, 0x6a, 0x23, 0x31,
	0x14, 0x85, 0x99, 0xf1, 0xef, 0x5c, 0xdb, 0xcb, 0xae, 0xd8, 0x42, 0x2c, 0x2c, 0x36, 0x4e, 0x63,
	0x08, 0xf1, 0x14, 0x69, 0x52, 0x87, 0xb4, 0x49, 0x61, 0x52, 0xa5, 0x31, 0xb2, 0xe6, 0x32, 0x56,
	0x18, 0x49, 0x83, 0x24, 0x93, 0x3c, 0x44, 0x1e, 0x34, 0x8f, 0x11, 0x74, 0x35, 0x76, 0x7e, 0x48,
	0x93, 0xee, 0x9e, 0x73, 0x3e, 0x49, 0xe7, 0x0e, 0x03, 0x57, 0xb5, 0x0a, 0x88, 0x6b, 0x69, 0x75,
	0xf9, 0xa8, 0x4c, 0xed, 0xf7, 0xc2, 0x48, 0x29, 0x4b, 0x69, 0x0f, 0xce, 0x63, 0x79, 0xf0, 0xe8,
	0xca, 0xd6, 0xd9, 0x60, 0xcb, 0x2a, 0xd8, 0x52, 0xa3, 0xde, 0xa1, 0x5b, 0x93, 0xc1, 0xfa, 0x31,
	0x5c, 0xbe, 0x64, 0xf0, 0xe7, 0x96, 0xec, 0x0d, 0xd6, 0xca, 0x07, 0x74, 0x37, 0xc1, 0xb2, 0xbf,
	0x30, 0x40, 0x2d, 0x54, 0xc3, 0xb3, 0x45, 0xb6, 0x2a, 0x36, 0x49, 0xb0, 0x7f, 0x30, 0x6e, 0x85,
	0xf7, 0x4f, 0xd6, 0x55, 0x3c, 0xa7, 0xe0, 0xa4, 0x19, 0x83, 0xbe, 0x11, 0x1a, 0x79, 0x8f, 0x7c,
	0x9a, 0xa3, 0x27, 0x6d, 0x85, 0xbc, 0x9f, 0xbc, 0x38, 0xb3, 0xff, 0x00, 0x8d, 0xad, 0x95, 0xd9,
	0x12, 0x3d, 0xa0, 0xa4, 0x20, 0xe7, 0x4e, 0x68, 0x5c, 0xbe, 0xe6, 0x50, 0xa4, 0x3a, 0xb1, 0xc6,
	0x2f, 0xc8, 0x55, 0xd5, 0x75, 0xc8, 0x55, 0xf5, 0x5e, 0x2b, 0xff, 0x58, 0xeb, 0xbb, 0xa7, 0x7f,
	0x43, 0xcf, 0xe3, 0x73, 0xf7, 0x72, 0x1c, 0xe3, 0xd9, 0x76, 0x6f, 0x83, 0xed, 0xde, 0x4c, 0x22,
	0xae, 0xa4, 0x4c, 0xc0, 0xda, 0x89, 0x86, 0x0f, 0x17, 0xd9, 0x6a, 0xb6, 0x39, 0x69, 0x76, 0x06,
	0xb3, 0x06, 0x85, 0x33, 0xca, 0xd4, 0xdb, 0xa0, 0x34, 0xf2, 0x11, 0x01, 0xd3, 0xa3, 0x79, 0xaf,
	0x34, 0x46, 0xc8, 0x75, 0x1f, 0x2e, 0x41, 0x63, 0xba, 0x7e, 0x7a, 0x34, 0x09, 0xfa, 0xbc, 0x74,
	0xf1, 0x65, 0x69, 0x36, 0x87, 0x89, 0x74, 0x28, 0x02, 0xa6, 0x1b, 0x80, 0x72, 0x48, 0x16, 0x9d,
	0x9f, 0xc3, 0xe4, 0xd0, 0x56, 0x27, 0x60, 0x92, 0x80, 0x64, 0x11, 0xc0, 0x61, 0x44, 0xb8, 0x75,
	0x7c, 0x4a, 0xe1, 0x51, 0xc6, 0x24, 0x71, 0x8e, 0xcf, 0x52, 0xd2, 0xc9, 0xeb, 0x8b, 0x87, 0xf3,
	0x1f, 0xfc, 0x3b, 0xbb, 0x21, 0x8d, 0x97, 0x6f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x69, 0x3e, 0x36,
	0xe2, 0x71, 0x02, 0x00, 0x00,
}
