// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.7
// source: gitee.com/jingshanccc/course/user/proto/dto/member.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberRegisterDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email     string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password  string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Code      string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"` //邮件验证码
	LoginName string `protobuf:"bytes,5,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
}

func (x *MemberRegisterDto) Reset() {
	*x = MemberRegisterDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberRegisterDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRegisterDto) ProtoMessage() {}

func (x *MemberRegisterDto) ProtoReflect() protoreflect.Message {
	mi := &file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRegisterDto.ProtoReflect.Descriptor instead.
func (*MemberRegisterDto) Descriptor() ([]byte, []int) {
	return file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_rawDescGZIP(), []int{0}
}

func (x *MemberRegisterDto) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MemberRegisterDto) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *MemberRegisterDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemberRegisterDto) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MemberRegisterDto) GetLoginName() string {
	if x != nil {
		return x.LoginName
	}
	return ""
}

type MemberDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email        string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Sex          string `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Photo        string `protobuf:"bytes,5,opt,name=photo,proto3" json:"photo,omitempty"`
	Integral     uint32 `protobuf:"varint,6,opt,name=integral,proto3" json:"integral,omitempty"`
	LearningTime uint32 `protobuf:"varint,7,opt,name=learning_time,json=learningTime,proto3" json:"learning_time,omitempty"`
	RegisterTime string `protobuf:"bytes,8,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
}

func (x *MemberDto) Reset() {
	*x = MemberDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberDto) ProtoMessage() {}

func (x *MemberDto) ProtoReflect() protoreflect.Message {
	mi := &file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberDto.ProtoReflect.Descriptor instead.
func (*MemberDto) Descriptor() ([]byte, []int) {
	return file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_rawDescGZIP(), []int{1}
}

func (x *MemberDto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemberDto) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MemberDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemberDto) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *MemberDto) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *MemberDto) GetIntegral() uint32 {
	if x != nil {
		return x.Integral
	}
	return 0
}

func (x *MemberDto) GetLearningTime() uint32 {
	if x != nil {
		return x.LearningTime
	}
	return 0
}

func (x *MemberDto) GetRegisterTime() string {
	if x != nil {
		return x.RegisterTime
	}
	return ""
}

var File_gitee_com_jingshanccc_course_user_proto_dto_member_proto protoreflect.FileDescriptor

var file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_rawDesc = []byte{
	0x0a, 0x38, 0x67, 0x69, 0x74, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x69, 0x6e, 0x67,
	0x73, 0x68, 0x61, 0x6e, 0x63, 0x63, 0x63, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x74, 0x6f, 0x2f, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x22, 0x8c, 0x01, 0x0a, 0x11, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0xd3, 0x01, 0x0a, 0x09, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f,
	0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x6c,
	0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0c, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x65, 0x65, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6a, 0x69, 0x6e, 0x67, 0x73, 0x68, 0x61, 0x6e, 0x63, 0x63, 0x63, 0x2f, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x64, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_rawDescOnce sync.Once
	file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_rawDescData = file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_rawDesc
)

func file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_rawDescGZIP() []byte {
	file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_rawDescOnce.Do(func() {
		file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_rawDescData = protoimpl.X.CompressGZIP(file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_rawDescData)
	})
	return file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_rawDescData
}

var file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_goTypes = []interface{}{
	(*MemberRegisterDto)(nil), // 0: user.MemberRegisterDto
	(*MemberDto)(nil),         // 1: user.MemberDto
}
var file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_init() }
func file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_init() {
	if File_gitee_com_jingshanccc_course_user_proto_dto_member_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberRegisterDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_goTypes,
		DependencyIndexes: file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_depIdxs,
		MessageInfos:      file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_msgTypes,
	}.Build()
	File_gitee_com_jingshanccc_course_user_proto_dto_member_proto = out.File
	file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_rawDesc = nil
	file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_goTypes = nil
	file_gitee_com_jingshanccc_course_user_proto_dto_member_proto_depIdxs = nil
}
