// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gitee.com/jingshanccc/course/user/proto/dto/user.proto

package dto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserDto struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LoginName            string   `protobuf:"bytes,3,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	AvatarName           string   `protobuf:"bytes,6,opt,name=avatar_name,json=avatarName,proto3" json:"avatar_name,omitempty"`
	AvatarPath           string   `protobuf:"bytes,7,opt,name=avatar_path,json=avatarPath,proto3" json:"avatar_path,omitempty"`
	Gender               string   `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
	IsAdmin              bool     `protobuf:"varint,9,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	CreateBy             string   `protobuf:"bytes,10,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	CreateTime           string   `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateBy             string   `protobuf:"bytes,12,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	UpdateTime           string   `protobuf:"bytes,13,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Roles                string   `protobuf:"bytes,14,opt,name=roles,proto3" json:"roles,omitempty"`
	Permissions          []string `protobuf:"bytes,15,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDto) Reset()         { *m = UserDto{} }
func (m *UserDto) String() string { return proto.CompactTextString(m) }
func (*UserDto) ProtoMessage()    {}
func (*UserDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_120bd965a4745ce9, []int{0}
}

func (m *UserDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDto.Unmarshal(m, b)
}
func (m *UserDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDto.Marshal(b, m, deterministic)
}
func (m *UserDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDto.Merge(m, src)
}
func (m *UserDto) XXX_Size() int {
	return xxx_messageInfo_UserDto.Size(m)
}
func (m *UserDto) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDto.DiscardUnknown(m)
}

var xxx_messageInfo_UserDto proto.InternalMessageInfo

func (m *UserDto) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserDto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserDto) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *UserDto) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserDto) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserDto) GetAvatarName() string {
	if m != nil {
		return m.AvatarName
	}
	return ""
}

func (m *UserDto) GetAvatarPath() string {
	if m != nil {
		return m.AvatarPath
	}
	return ""
}

func (m *UserDto) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UserDto) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *UserDto) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

func (m *UserDto) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *UserDto) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func (m *UserDto) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *UserDto) GetRoles() string {
	if m != nil {
		return m.Roles
	}
	return ""
}

func (m *UserDto) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type PageDto struct {
	Page                 int64      `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64      `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sort                 []string   `protobuf:"bytes,3,rep,name=sort,proto3" json:"sort,omitempty"`
	Blurry               string     `protobuf:"bytes,4,opt,name=blurry,proto3" json:"blurry,omitempty"`
	CreateTime           []string   `protobuf:"bytes,5,rep,name=createTime,proto3" json:"createTime,omitempty"`
	Total                int64      `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Rows                 []*UserDto `protobuf:"bytes,7,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PageDto) Reset()         { *m = PageDto{} }
func (m *PageDto) String() string { return proto.CompactTextString(m) }
func (*PageDto) ProtoMessage()    {}
func (*PageDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_120bd965a4745ce9, []int{1}
}

func (m *PageDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageDto.Unmarshal(m, b)
}
func (m *PageDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageDto.Marshal(b, m, deterministic)
}
func (m *PageDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageDto.Merge(m, src)
}
func (m *PageDto) XXX_Size() int {
	return xxx_messageInfo_PageDto.Size(m)
}
func (m *PageDto) XXX_DiscardUnknown() {
	xxx_messageInfo_PageDto.DiscardUnknown(m)
}

var xxx_messageInfo_PageDto proto.InternalMessageInfo

func (m *PageDto) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageDto) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PageDto) GetSort() []string {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *PageDto) GetBlurry() string {
	if m != nil {
		return m.Blurry
	}
	return ""
}

func (m *PageDto) GetCreateTime() []string {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *PageDto) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PageDto) GetRows() []*UserDto {
	if m != nil {
		return m.Rows
	}
	return nil
}

type LoginUserDto struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LoginName            string   `protobuf:"bytes,2,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserDto) Reset()         { *m = LoginUserDto{} }
func (m *LoginUserDto) String() string { return proto.CompactTextString(m) }
func (*LoginUserDto) ProtoMessage()    {}
func (*LoginUserDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_120bd965a4745ce9, []int{2}
}

func (m *LoginUserDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserDto.Unmarshal(m, b)
}
func (m *LoginUserDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserDto.Marshal(b, m, deterministic)
}
func (m *LoginUserDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserDto.Merge(m, src)
}
func (m *LoginUserDto) XXX_Size() int {
	return xxx_messageInfo_LoginUserDto.Size(m)
}
func (m *LoginUserDto) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserDto.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserDto proto.InternalMessageInfo

func (m *LoginUserDto) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LoginUserDto) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *LoginUserDto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginUserDto) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginUserDto) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdatePass struct {
	OldPass              string   `protobuf:"bytes,1,opt,name=oldPass,proto3" json:"oldPass,omitempty"`
	NewPass              string   `protobuf:"bytes,2,opt,name=newPass,proto3" json:"newPass,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	IsMember             bool     `protobuf:"varint,4,opt,name=isMember,proto3" json:"isMember,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePass) Reset()         { *m = UpdatePass{} }
func (m *UpdatePass) String() string { return proto.CompactTextString(m) }
func (*UpdatePass) ProtoMessage()    {}
func (*UpdatePass) Descriptor() ([]byte, []int) {
	return fileDescriptor_120bd965a4745ce9, []int{3}
}

func (m *UpdatePass) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePass.Unmarshal(m, b)
}
func (m *UpdatePass) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePass.Marshal(b, m, deterministic)
}
func (m *UpdatePass) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePass.Merge(m, src)
}
func (m *UpdatePass) XXX_Size() int {
	return xxx_messageInfo_UpdatePass.Size(m)
}
func (m *UpdatePass) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePass.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePass proto.InternalMessageInfo

func (m *UpdatePass) GetOldPass() string {
	if m != nil {
		return m.OldPass
	}
	return ""
}

func (m *UpdatePass) GetNewPass() string {
	if m != nil {
		return m.NewPass
	}
	return ""
}

func (m *UpdatePass) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdatePass) GetIsMember() bool {
	if m != nil {
		return m.IsMember
	}
	return false
}

type UpdateEmail struct {
	Pass                 string   `protobuf:"bytes,1,opt,name=pass,proto3" json:"pass,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	IsMember             bool     `protobuf:"varint,5,opt,name=isMember,proto3" json:"isMember,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEmail) Reset()         { *m = UpdateEmail{} }
func (m *UpdateEmail) String() string { return proto.CompactTextString(m) }
func (*UpdateEmail) ProtoMessage()    {}
func (*UpdateEmail) Descriptor() ([]byte, []int) {
	return fileDescriptor_120bd965a4745ce9, []int{4}
}

func (m *UpdateEmail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmail.Unmarshal(m, b)
}
func (m *UpdateEmail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmail.Marshal(b, m, deterministic)
}
func (m *UpdateEmail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmail.Merge(m, src)
}
func (m *UpdateEmail) XXX_Size() int {
	return xxx_messageInfo_UpdateEmail.Size(m)
}
func (m *UpdateEmail) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmail.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmail proto.InternalMessageInfo

func (m *UpdateEmail) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

func (m *UpdateEmail) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateEmail) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *UpdateEmail) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateEmail) GetIsMember() bool {
	if m != nil {
		return m.IsMember
	}
	return false
}

func init() {
	proto.RegisterType((*UserDto)(nil), "user.UserDto")
	proto.RegisterType((*PageDto)(nil), "user.PageDto")
	proto.RegisterType((*LoginUserDto)(nil), "user.LoginUserDto")
	proto.RegisterType((*UpdatePass)(nil), "user.UpdatePass")
	proto.RegisterType((*UpdateEmail)(nil), "user.UpdateEmail")
}

func init() {
	proto.RegisterFile("gitee.com/jingshanccc/course/user/proto/dto/user.proto", fileDescriptor_120bd965a4745ce9)
}

var fileDescriptor_120bd965a4745ce9 = []byte{
	// 544 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x55, 0x9b, 0x64, 0x93, 0x4e, 0x77, 0x17, 0xc9, 0xaa, 0x90, 0x01, 0x01, 0xa5, 0xa7, 0x4a,
	0x88, 0x56, 0x02, 0x89, 0x3b, 0x2b, 0x38, 0x20, 0x01, 0xaa, 0x22, 0xf6, 0xc2, 0xa5, 0x72, 0x93,
	0x51, 0x6a, 0x48, 0xe2, 0xc8, 0x76, 0xa9, 0xca, 0x85, 0x03, 0x5f, 0xc2, 0x4f, 0xf0, 0x7d, 0xc8,
	0x63, 0xb7, 0x9b, 0x45, 0xda, 0x03, 0xb7, 0x79, 0xef, 0xf5, 0x79, 0xc6, 0x9e, 0x97, 0xc2, 0xeb,
	0x4a, 0x5a, 0xc4, 0x45, 0xa1, 0x9a, 0xe5, 0x57, 0xd9, 0x56, 0x66, 0x2b, 0xda, 0xa2, 0x28, 0x96,
	0x85, 0xda, 0x69, 0x83, 0xcb, 0x9d, 0x41, 0xbd, 0xec, 0xb4, 0xb2, 0x6a, 0x59, 0x5a, 0x45, 0x70,
	0x41, 0x90, 0xc5, 0xae, 0x9e, 0xfd, 0x8e, 0x20, 0xbd, 0x36, 0xa8, 0xdf, 0x5a, 0xc5, 0x2e, 0x61,
	0x28, 0x4b, 0x3e, 0x98, 0x0e, 0xe6, 0xa3, 0x7c, 0x28, 0x4b, 0xc6, 0x20, 0x6e, 0x45, 0x83, 0x7c,
	0x48, 0x0c, 0xd5, 0xec, 0x31, 0x40, 0xad, 0x2a, 0xd9, 0xae, 0x49, 0x89, 0x48, 0x19, 0x11, 0xf3,
	0xc9, 0xc9, 0x13, 0x48, 0xba, 0xad, 0x6a, 0x91, 0xc7, 0xa4, 0x78, 0xe0, 0x58, 0x6c, 0x84, 0xac,
	0x79, 0xe2, 0x59, 0x02, 0xec, 0x29, 0x8c, 0xc5, 0x77, 0x61, 0x85, 0xf6, 0x67, 0x9d, 0x91, 0x06,
	0x9e, 0xa2, 0xc3, 0x6e, 0x7e, 0xd0, 0x09, 0xbb, 0xe5, 0x69, 0xff, 0x07, 0x2b, 0x61, 0xb7, 0xec,
	0x3e, 0x9c, 0x55, 0xd8, 0x96, 0xa8, 0x79, 0x46, 0x5a, 0x40, 0xec, 0x01, 0x64, 0xd2, 0xac, 0x45,
	0xd9, 0xc8, 0x96, 0x8f, 0xa6, 0x83, 0x79, 0x96, 0xa7, 0xd2, 0xbc, 0x71, 0x90, 0x3d, 0x82, 0x51,
	0xa1, 0x51, 0x58, 0x5c, 0x6f, 0x0e, 0x1c, 0xc8, 0x95, 0x79, 0xe2, 0xea, 0xe0, 0x1a, 0x06, 0xd1,
	0xca, 0x06, 0xf9, 0xd8, 0x37, 0xf4, 0xd4, 0x67, 0xd9, 0xa0, 0x73, 0xef, 0xba, 0x32, 0xb8, 0xcf,
	0xbd, 0xdb, 0x13, 0xde, 0x1d, 0x44, 0x72, 0x5f, 0x78, 0xb7, 0xa7, 0xc8, 0x3d, 0x81, 0x44, 0xab,
	0x1a, 0x0d, 0xbf, 0xf4, 0xcf, 0x40, 0x80, 0x4d, 0x61, 0xdc, 0xa1, 0x6e, 0xa4, 0x31, 0x52, 0xb5,
	0x86, 0xdf, 0x9b, 0x46, 0xf3, 0x51, 0xde, 0xa7, 0x66, 0x7f, 0x06, 0x90, 0xae, 0x44, 0x85, 0x6e,
	0x47, 0x0c, 0xe2, 0x4e, 0x54, 0x48, 0x5b, 0x8a, 0x72, 0xaa, 0x1d, 0x67, 0xe4, 0x0f, 0xbf, 0xa7,
	0x28, 0xa7, 0x9a, 0x38, 0xa5, 0x2d, 0x8f, 0xe8, 0x38, 0xaa, 0xdd, 0x73, 0x6d, 0xea, 0x9d, 0xd6,
	0x87, 0xb0, 0x9d, 0x80, 0xd8, 0x13, 0xe8, 0xdd, 0x91, 0x27, 0xe4, 0xe8, 0xdf, 0x7a, 0x02, 0x89,
	0x55, 0x56, 0xd4, 0xb4, 0xa2, 0x28, 0xf7, 0x80, 0x3d, 0x83, 0x58, 0xab, 0xbd, 0xe1, 0xe9, 0x34,
	0x9a, 0x8f, 0x5f, 0x5e, 0x2c, 0x28, 0x5a, 0x21, 0x4a, 0x39, 0x49, 0xb3, 0x5f, 0x03, 0x38, 0xff,
	0xe0, 0xb2, 0x71, 0x57, 0xc2, 0x6e, 0xa7, 0x69, 0xf8, 0x6f, 0x9a, 0x8e, 0x01, 0x8c, 0x7a, 0x01,
	0xa4, 0x61, 0xbe, 0x61, 0x7b, 0x4c, 0x18, 0x01, 0xf6, 0x10, 0xb2, 0x4e, 0x18, 0xb3, 0x57, 0xba,
	0x0c, 0x21, 0x3b, 0xe1, 0x99, 0x05, 0xb8, 0xa6, 0x25, 0xac, 0x84, 0x31, 0x8c, 0x43, 0xaa, 0xea,
	0xd2, 0x95, 0x61, 0x8e, 0x23, 0x74, 0x4a, 0x8b, 0x7b, 0x52, 0xfc, 0x24, 0x47, 0xe8, 0x1e, 0xce,
	0xdd, 0xee, 0x7d, 0x19, 0x26, 0x09, 0xc8, 0x75, 0x95, 0xe6, 0x23, 0x36, 0x1b, 0xd4, 0x34, 0x4e,
	0x96, 0x9f, 0xf0, 0xec, 0x27, 0x8c, 0x7d, 0xd7, 0x77, 0x14, 0x76, 0xda, 0xdb, 0xa9, 0x27, 0xd5,
	0x37, 0x9f, 0xc5, 0xb0, 0xff, 0x59, 0x30, 0x88, 0x0b, 0x55, 0x9e, 0x2e, 0xed, 0xea, 0xde, 0x00,
	0xf1, 0x9d, 0x03, 0x24, 0xb7, 0x07, 0xb8, 0x7a, 0xf1, 0xe5, 0xf9, 0x7f, 0xfc, 0x33, 0x6c, 0xce,
	0xa8, 0x7c, 0xf5, 0x37, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x77, 0x46, 0xf2, 0x4f, 0x04, 0x00, 0x00,
}
