// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: user-dto.proto

package user

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LoginUserDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LoginName string         `protobuf:"bytes,2,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	Name      string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Token     string         `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Resources []*ResourceDto `protobuf:"bytes,5,rep,name=resources,proto3" json:"resources,omitempty"`
	Requests  []string       `protobuf:"bytes,6,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *LoginUserDto) Reset() {
	*x = LoginUserDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_dto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginUserDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserDto) ProtoMessage() {}

func (x *LoginUserDto) ProtoReflect() protoreflect.Message {
	mi := &file_user_dto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserDto.ProtoReflect.Descriptor instead.
func (*LoginUserDto) Descriptor() ([]byte, []int) {
	return file_user_dto_proto_rawDescGZIP(), []int{0}
}

func (x *LoginUserDto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoginUserDto) GetLoginName() string {
	if x != nil {
		return x.LoginName
	}
	return ""
}

func (x *LoginUserDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginUserDto) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginUserDto) GetResources() []*ResourceDto {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *LoginUserDto) GetRequests() []string {
	if x != nil {
		return x.Requests
	}
	return nil
}

type ResourceDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//
	// id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//
	// 名称|菜单或按钮
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//
	// 页面|路由
	Page string `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	//
	// 请求|接口
	Request string `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	//
	// 父id
	Parent   string         `protobuf:"bytes,5,opt,name=parent,proto3" json:"parent,omitempty"`
	Children []*ResourceDto `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *ResourceDto) Reset() {
	*x = ResourceDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_dto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDto) ProtoMessage() {}

func (x *ResourceDto) ProtoReflect() protoreflect.Message {
	mi := &file_user_dto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDto.ProtoReflect.Descriptor instead.
func (*ResourceDto) Descriptor() ([]byte, []int) {
	return file_user_dto_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceDto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceDto) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *ResourceDto) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *ResourceDto) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ResourceDto) GetChildren() []*ResourceDto {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_user_dto_proto protoreflect.FileDescriptor

var file_user_dto_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x64, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x22, 0xc4, 0x01, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x3f, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x2e, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x44, 0x74, 0x6f, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0xb6, 0x01,
	0x0a, 0x0b, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64,
	0x72, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x63, 0x68, 0x61, 0x6e, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x74, 0x6f, 0x52, 0x08, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x42, 0x0c, 0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_dto_proto_rawDescOnce sync.Once
	file_user_dto_proto_rawDescData = file_user_dto_proto_rawDesc
)

func file_user_dto_proto_rawDescGZIP() []byte {
	file_user_dto_proto_rawDescOnce.Do(func() {
		file_user_dto_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_dto_proto_rawDescData)
	})
	return file_user_dto_proto_rawDescData
}

var file_user_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_dto_proto_goTypes = []interface{}{
	(*LoginUserDto)(nil), // 0: com.chan.course.user.LoginUserDto
	(*ResourceDto)(nil),  // 1: com.chan.course.user.ResourceDto
}
var file_user_dto_proto_depIdxs = []int32{
	1, // 0: com.chan.course.user.LoginUserDto.resources:type_name -> com.chan.course.user.ResourceDto
	1, // 1: com.chan.course.user.ResourceDto.children:type_name -> com.chan.course.user.ResourceDto
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_dto_proto_init() }
func file_user_dto_proto_init() {
	if File_user_dto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_dto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginUserDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_dto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_dto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_dto_proto_goTypes,
		DependencyIndexes: file_user_dto_proto_depIdxs,
		MessageInfos:      file_user_dto_proto_msgTypes,
	}.Build()
	File_user_dto_proto = out.File
	file_user_dto_proto_rawDesc = nil
	file_user_dto_proto_goTypes = nil
	file_user_dto_proto_depIdxs = nil
}
