// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: course/user-srv/proto/user/user.proto

package user

import (
	dto "course/user-srv/proto/dto"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserService service

type UserService interface {
	// 用户接口
	List(ctx context.Context, in *PageDto, opts ...client.CallOption) (*PageDto, error)
	Save(ctx context.Context, in *UserDto, opts ...client.CallOption) (*UserDto, error)
	Delete(ctx context.Context, in *dto.String, opts ...client.CallOption) (*dto.String, error)
	SavePassword(ctx context.Context, in *UserDto, opts ...client.CallOption) (*UserDto, error)
	Login(ctx context.Context, in *UserDto, opts ...client.CallOption) (*dto.LoginUserDto, error)
	Logout(ctx context.Context, in *dto.String, opts ...client.CallOption) (*dto.String, error)
	//权限管理
	LoadTree(ctx context.Context, in *dto.String, opts ...client.CallOption) (*dto.ResourceDtoList, error)
	SaveJson(ctx context.Context, in *dto.String, opts ...client.CallOption) (*dto.String, error)
	DeleteResource(ctx context.Context, in *dto.String, opts ...client.CallOption) (*dto.String, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) List(ctx context.Context, in *PageDto, opts ...client.CallOption) (*PageDto, error) {
	req := c.c.NewRequest(c.name, "UserService.List", in)
	out := new(PageDto)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Save(ctx context.Context, in *UserDto, opts ...client.CallOption) (*UserDto, error) {
	req := c.c.NewRequest(c.name, "UserService.Save", in)
	out := new(UserDto)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Delete(ctx context.Context, in *dto.String, opts ...client.CallOption) (*dto.String, error) {
	req := c.c.NewRequest(c.name, "UserService.Delete", in)
	out := new(dto.String)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SavePassword(ctx context.Context, in *UserDto, opts ...client.CallOption) (*UserDto, error) {
	req := c.c.NewRequest(c.name, "UserService.SavePassword", in)
	out := new(UserDto)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Login(ctx context.Context, in *UserDto, opts ...client.CallOption) (*dto.LoginUserDto, error) {
	req := c.c.NewRequest(c.name, "UserService.Login", in)
	out := new(dto.LoginUserDto)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Logout(ctx context.Context, in *dto.String, opts ...client.CallOption) (*dto.String, error) {
	req := c.c.NewRequest(c.name, "UserService.Logout", in)
	out := new(dto.String)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) LoadTree(ctx context.Context, in *dto.String, opts ...client.CallOption) (*dto.ResourceDtoList, error) {
	req := c.c.NewRequest(c.name, "UserService.LoadTree", in)
	out := new(dto.ResourceDtoList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SaveJson(ctx context.Context, in *dto.String, opts ...client.CallOption) (*dto.String, error) {
	req := c.c.NewRequest(c.name, "UserService.SaveJson", in)
	out := new(dto.String)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) DeleteResource(ctx context.Context, in *dto.String, opts ...client.CallOption) (*dto.String, error) {
	req := c.c.NewRequest(c.name, "UserService.DeleteResource", in)
	out := new(dto.String)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	// 用户接口
	List(context.Context, *PageDto, *PageDto) error
	Save(context.Context, *UserDto, *UserDto) error
	Delete(context.Context, *dto.String, *dto.String) error
	SavePassword(context.Context, *UserDto, *UserDto) error
	Login(context.Context, *UserDto, *dto.LoginUserDto) error
	Logout(context.Context, *dto.String, *dto.String) error
	//权限管理
	LoadTree(context.Context, *dto.String, *dto.ResourceDtoList) error
	SaveJson(context.Context, *dto.String, *dto.String) error
	DeleteResource(context.Context, *dto.String, *dto.String) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		List(ctx context.Context, in *PageDto, out *PageDto) error
		Save(ctx context.Context, in *UserDto, out *UserDto) error
		Delete(ctx context.Context, in *dto.String, out *dto.String) error
		SavePassword(ctx context.Context, in *UserDto, out *UserDto) error
		Login(ctx context.Context, in *UserDto, out *dto.LoginUserDto) error
		Logout(ctx context.Context, in *dto.String, out *dto.String) error
		LoadTree(ctx context.Context, in *dto.String, out *dto.ResourceDtoList) error
		SaveJson(ctx context.Context, in *dto.String, out *dto.String) error
		DeleteResource(ctx context.Context, in *dto.String, out *dto.String) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) List(ctx context.Context, in *PageDto, out *PageDto) error {
	return h.UserServiceHandler.List(ctx, in, out)
}

func (h *userServiceHandler) Save(ctx context.Context, in *UserDto, out *UserDto) error {
	return h.UserServiceHandler.Save(ctx, in, out)
}

func (h *userServiceHandler) Delete(ctx context.Context, in *dto.String, out *dto.String) error {
	return h.UserServiceHandler.Delete(ctx, in, out)
}

func (h *userServiceHandler) SavePassword(ctx context.Context, in *UserDto, out *UserDto) error {
	return h.UserServiceHandler.SavePassword(ctx, in, out)
}

func (h *userServiceHandler) Login(ctx context.Context, in *UserDto, out *dto.LoginUserDto) error {
	return h.UserServiceHandler.Login(ctx, in, out)
}

func (h *userServiceHandler) Logout(ctx context.Context, in *dto.String, out *dto.String) error {
	return h.UserServiceHandler.Logout(ctx, in, out)
}

func (h *userServiceHandler) LoadTree(ctx context.Context, in *dto.String, out *dto.ResourceDtoList) error {
	return h.UserServiceHandler.LoadTree(ctx, in, out)
}

func (h *userServiceHandler) SaveJson(ctx context.Context, in *dto.String, out *dto.String) error {
	return h.UserServiceHandler.SaveJson(ctx, in, out)
}

func (h *userServiceHandler) DeleteResource(ctx context.Context, in *dto.String, out *dto.String) error {
	return h.UserServiceHandler.DeleteResource(ctx, in, out)
}
