// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: course/file-srv/proto/file/file.proto

package file

import (
	dto "course/file-srv/proto/dto"
	basic "course/proto/basic"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for FileService service

func NewFileServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for FileService service

type FileService interface {
	Upload(ctx context.Context, in *dto.FileDto, opts ...client.CallOption) (*dto.FileDto, error)
	Check(ctx context.Context, in *basic.String, opts ...client.CallOption) (*dto.FileDto, error)
}

type fileService struct {
	c    client.Client
	name string
}

func NewFileService(name string, c client.Client) FileService {
	return &fileService{
		c:    c,
		name: name,
	}
}

func (c *fileService) Upload(ctx context.Context, in *dto.FileDto, opts ...client.CallOption) (*dto.FileDto, error) {
	req := c.c.NewRequest(c.name, "FileService.Upload", in)
	out := new(dto.FileDto)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileService) Check(ctx context.Context, in *basic.String, opts ...client.CallOption) (*dto.FileDto, error) {
	req := c.c.NewRequest(c.name, "FileService.Check", in)
	out := new(dto.FileDto)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FileService service

type FileServiceHandler interface {
	Upload(context.Context, *dto.FileDto, *dto.FileDto) error
	Check(context.Context, *basic.String, *dto.FileDto) error
}

func RegisterFileServiceHandler(s server.Server, hdlr FileServiceHandler, opts ...server.HandlerOption) error {
	type fileService interface {
		Upload(ctx context.Context, in *dto.FileDto, out *dto.FileDto) error
		Check(ctx context.Context, in *basic.String, out *dto.FileDto) error
	}
	type FileService struct {
		fileService
	}
	h := &fileServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&FileService{h}, opts...))
}

type fileServiceHandler struct {
	FileServiceHandler
}

func (h *fileServiceHandler) Upload(ctx context.Context, in *dto.FileDto, out *dto.FileDto) error {
	return h.FileServiceHandler.Upload(ctx, in, out)
}

func (h *fileServiceHandler) Check(ctx context.Context, in *basic.String, out *dto.FileDto) error {
	return h.FileServiceHandler.Check(ctx, in, out)
}
