// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gitee.com/jingshanccc/course/course/proto/dto/course.proto

package dto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Course Dto
type CourseDto struct {
	//
	// id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//
	// 名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//
	// 概述
	Summary string `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	//
	// 时长|单位秒
	Time int32 `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	//
	// 价格（元）
	Price float64 `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	//
	// 封面
	Image string `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	//
	// 级别|枚举[CourseLevelEnum]：ONE("1", "初级"),TWO("2", "中级"),THREE("3", "高级")
	Level string `protobuf:"bytes,7,opt,name=level,proto3" json:"level,omitempty"`
	//
	// 收费|枚举[CourseChargeEnum]：CHARGE("C", "收费"),FREE("F", "免费")
	Charge string `protobuf:"bytes,8,opt,name=charge,proto3" json:"charge,omitempty"`
	//
	// 状态|枚举[CourseStatusEnum]：PUBLISH("P", "发布"),DRAFT("D", "草稿")
	Status string `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	//
	// 报名数
	Enroll int32 `protobuf:"varint,10,opt,name=enroll,proto3" json:"enroll,omitempty"`
	//
	// 顺序
	Sort int32 `protobuf:"varint,11,opt,name=sort,proto3" json:"sort,omitempty"`
	//
	// 创建时间
	CreatedAt string `protobuf:"bytes,12,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	//
	// 修改时间
	UpdatedAt  string        `protobuf:"bytes,13,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Categories []string      `protobuf:"bytes,14,rep,name=categories,proto3" json:"categories,omitempty"`
	Chapters   []*ChapterDto `protobuf:"bytes,15,rep,name=chapters,proto3" json:"chapters,omitempty"`
	Sections   []*SectionDto `protobuf:"bytes,16,rep,name=sections,proto3" json:"sections,omitempty"`
	Content    string        `protobuf:"bytes,17,opt,name=content,proto3" json:"content,omitempty"`
	Teacher    *TeacherDto   `protobuf:"bytes,18,opt,name=teacher,proto3" json:"teacher,omitempty"`
	//
	// 讲师|teacher.id
	TeacherId            string   `protobuf:"bytes,19,opt,name=teacherId,proto3" json:"teacherId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseDto) Reset()         { *m = CourseDto{} }
func (m *CourseDto) String() string { return proto.CompactTextString(m) }
func (*CourseDto) ProtoMessage()    {}
func (*CourseDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{0}
}

func (m *CourseDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseDto.Unmarshal(m, b)
}
func (m *CourseDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseDto.Marshal(b, m, deterministic)
}
func (m *CourseDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseDto.Merge(m, src)
}
func (m *CourseDto) XXX_Size() int {
	return xxx_messageInfo_CourseDto.Size(m)
}
func (m *CourseDto) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseDto.DiscardUnknown(m)
}

var xxx_messageInfo_CourseDto proto.InternalMessageInfo

func (m *CourseDto) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CourseDto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CourseDto) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *CourseDto) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *CourseDto) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CourseDto) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *CourseDto) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *CourseDto) GetCharge() string {
	if m != nil {
		return m.Charge
	}
	return ""
}

func (m *CourseDto) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CourseDto) GetEnroll() int32 {
	if m != nil {
		return m.Enroll
	}
	return 0
}

func (m *CourseDto) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *CourseDto) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *CourseDto) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *CourseDto) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *CourseDto) GetChapters() []*ChapterDto {
	if m != nil {
		return m.Chapters
	}
	return nil
}

func (m *CourseDto) GetSections() []*SectionDto {
	if m != nil {
		return m.Sections
	}
	return nil
}

func (m *CourseDto) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CourseDto) GetTeacher() *TeacherDto {
	if m != nil {
		return m.Teacher
	}
	return nil
}

func (m *CourseDto) GetTeacherId() string {
	if m != nil {
		return m.TeacherId
	}
	return ""
}

type CoursePageDto struct {
	Page                 int64        `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64        `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sort                 []string     `protobuf:"bytes,3,rep,name=sort,proto3" json:"sort,omitempty"`
	Blurry               string       `protobuf:"bytes,4,opt,name=blurry,proto3" json:"blurry,omitempty"`
	Total                int64        `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	CreateTime           []string     `protobuf:"bytes,6,rep,name=createTime,proto3" json:"createTime,omitempty"`
	Rows                 []*CourseDto `protobuf:"bytes,7,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CoursePageDto) Reset()         { *m = CoursePageDto{} }
func (m *CoursePageDto) String() string { return proto.CompactTextString(m) }
func (*CoursePageDto) ProtoMessage()    {}
func (*CoursePageDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{1}
}

func (m *CoursePageDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoursePageDto.Unmarshal(m, b)
}
func (m *CoursePageDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoursePageDto.Marshal(b, m, deterministic)
}
func (m *CoursePageDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoursePageDto.Merge(m, src)
}
func (m *CoursePageDto) XXX_Size() int {
	return xxx_messageInfo_CoursePageDto.Size(m)
}
func (m *CoursePageDto) XXX_DiscardUnknown() {
	xxx_messageInfo_CoursePageDto.DiscardUnknown(m)
}

var xxx_messageInfo_CoursePageDto proto.InternalMessageInfo

func (m *CoursePageDto) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *CoursePageDto) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CoursePageDto) GetSort() []string {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *CoursePageDto) GetBlurry() string {
	if m != nil {
		return m.Blurry
	}
	return ""
}

func (m *CoursePageDto) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *CoursePageDto) GetCreateTime() []string {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *CoursePageDto) GetRows() []*CourseDto {
	if m != nil {
		return m.Rows
	}
	return nil
}

type CourseDtoList struct {
	Rows                 []*CourseDto `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CourseDtoList) Reset()         { *m = CourseDtoList{} }
func (m *CourseDtoList) String() string { return proto.CompactTextString(m) }
func (*CourseDtoList) ProtoMessage()    {}
func (*CourseDtoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{2}
}

func (m *CourseDtoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseDtoList.Unmarshal(m, b)
}
func (m *CourseDtoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseDtoList.Marshal(b, m, deterministic)
}
func (m *CourseDtoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseDtoList.Merge(m, src)
}
func (m *CourseDtoList) XXX_Size() int {
	return xxx_messageInfo_CourseDtoList.Size(m)
}
func (m *CourseDtoList) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseDtoList.DiscardUnknown(m)
}

var xxx_messageInfo_CourseDtoList proto.InternalMessageInfo

func (m *CourseDtoList) GetRows() []*CourseDto {
	if m != nil {
		return m.Rows
	}
	return nil
}

type CourseContentDto struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseContentDto) Reset()         { *m = CourseContentDto{} }
func (m *CourseContentDto) String() string { return proto.CompactTextString(m) }
func (*CourseContentDto) ProtoMessage()    {}
func (*CourseContentDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{3}
}

func (m *CourseContentDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseContentDto.Unmarshal(m, b)
}
func (m *CourseContentDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseContentDto.Marshal(b, m, deterministic)
}
func (m *CourseContentDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseContentDto.Merge(m, src)
}
func (m *CourseContentDto) XXX_Size() int {
	return xxx_messageInfo_CourseContentDto.Size(m)
}
func (m *CourseContentDto) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseContentDto.DiscardUnknown(m)
}

var xxx_messageInfo_CourseContentDto proto.InternalMessageInfo

func (m *CourseContentDto) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CourseContentDto) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CourseCategoryDto struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CourseId             string   `protobuf:"bytes,2,opt,name=CourseId,proto3" json:"CourseId,omitempty"`
	CategoryId           string   `protobuf:"bytes,3,opt,name=CategoryId,proto3" json:"CategoryId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseCategoryDto) Reset()         { *m = CourseCategoryDto{} }
func (m *CourseCategoryDto) String() string { return proto.CompactTextString(m) }
func (*CourseCategoryDto) ProtoMessage()    {}
func (*CourseCategoryDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{4}
}

func (m *CourseCategoryDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseCategoryDto.Unmarshal(m, b)
}
func (m *CourseCategoryDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseCategoryDto.Marshal(b, m, deterministic)
}
func (m *CourseCategoryDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseCategoryDto.Merge(m, src)
}
func (m *CourseCategoryDto) XXX_Size() int {
	return xxx_messageInfo_CourseCategoryDto.Size(m)
}
func (m *CourseCategoryDto) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseCategoryDto.DiscardUnknown(m)
}

var xxx_messageInfo_CourseCategoryDto proto.InternalMessageInfo

func (m *CourseCategoryDto) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CourseCategoryDto) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

func (m *CourseCategoryDto) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

type CourseCategoryDtoList struct {
	Rows                 []*CourseCategoryDto `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CourseCategoryDtoList) Reset()         { *m = CourseCategoryDtoList{} }
func (m *CourseCategoryDtoList) String() string { return proto.CompactTextString(m) }
func (*CourseCategoryDtoList) ProtoMessage()    {}
func (*CourseCategoryDtoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{5}
}

func (m *CourseCategoryDtoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseCategoryDtoList.Unmarshal(m, b)
}
func (m *CourseCategoryDtoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseCategoryDtoList.Marshal(b, m, deterministic)
}
func (m *CourseCategoryDtoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseCategoryDtoList.Merge(m, src)
}
func (m *CourseCategoryDtoList) XXX_Size() int {
	return xxx_messageInfo_CourseCategoryDtoList.Size(m)
}
func (m *CourseCategoryDtoList) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseCategoryDtoList.DiscardUnknown(m)
}

var xxx_messageInfo_CourseCategoryDtoList proto.InternalMessageInfo

func (m *CourseCategoryDtoList) GetRows() []*CourseCategoryDto {
	if m != nil {
		return m.Rows
	}
	return nil
}

type CategoryDto struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Parent               string   `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Sort                 int32    `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryDto) Reset()         { *m = CategoryDto{} }
func (m *CategoryDto) String() string { return proto.CompactTextString(m) }
func (*CategoryDto) ProtoMessage()    {}
func (*CategoryDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{6}
}

func (m *CategoryDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryDto.Unmarshal(m, b)
}
func (m *CategoryDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryDto.Marshal(b, m, deterministic)
}
func (m *CategoryDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryDto.Merge(m, src)
}
func (m *CategoryDto) XXX_Size() int {
	return xxx_messageInfo_CategoryDto.Size(m)
}
func (m *CategoryDto) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryDto.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryDto proto.InternalMessageInfo

func (m *CategoryDto) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CategoryDto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CategoryDto) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CategoryDto) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

type CategoryPageDto struct {
	Page                 int64          `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64          `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sort                 []string       `protobuf:"bytes,3,rep,name=sort,proto3" json:"sort,omitempty"`
	Blurry               string         `protobuf:"bytes,4,opt,name=blurry,proto3" json:"blurry,omitempty"`
	Total                int64          `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	Parent               string         `protobuf:"bytes,6,opt,name=parent,proto3" json:"parent,omitempty"`
	Rows                 []*CategoryDto `protobuf:"bytes,7,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CategoryPageDto) Reset()         { *m = CategoryPageDto{} }
func (m *CategoryPageDto) String() string { return proto.CompactTextString(m) }
func (*CategoryPageDto) ProtoMessage()    {}
func (*CategoryPageDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{7}
}

func (m *CategoryPageDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryPageDto.Unmarshal(m, b)
}
func (m *CategoryPageDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryPageDto.Marshal(b, m, deterministic)
}
func (m *CategoryPageDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryPageDto.Merge(m, src)
}
func (m *CategoryPageDto) XXX_Size() int {
	return xxx_messageInfo_CategoryPageDto.Size(m)
}
func (m *CategoryPageDto) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryPageDto.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryPageDto proto.InternalMessageInfo

func (m *CategoryPageDto) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *CategoryPageDto) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CategoryPageDto) GetSort() []string {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *CategoryPageDto) GetBlurry() string {
	if m != nil {
		return m.Blurry
	}
	return ""
}

func (m *CategoryPageDto) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *CategoryPageDto) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CategoryPageDto) GetRows() []*CategoryDto {
	if m != nil {
		return m.Rows
	}
	return nil
}

type CategoryDtoList struct {
	Rows                 []*CategoryDto `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CategoryDtoList) Reset()         { *m = CategoryDtoList{} }
func (m *CategoryDtoList) String() string { return proto.CompactTextString(m) }
func (*CategoryDtoList) ProtoMessage()    {}
func (*CategoryDtoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{8}
}

func (m *CategoryDtoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryDtoList.Unmarshal(m, b)
}
func (m *CategoryDtoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryDtoList.Marshal(b, m, deterministic)
}
func (m *CategoryDtoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryDtoList.Merge(m, src)
}
func (m *CategoryDtoList) XXX_Size() int {
	return xxx_messageInfo_CategoryDtoList.Size(m)
}
func (m *CategoryDtoList) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryDtoList.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryDtoList proto.InternalMessageInfo

func (m *CategoryDtoList) GetRows() []*CategoryDto {
	if m != nil {
		return m.Rows
	}
	return nil
}

//Chapter Dto
type ChapterDto struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId             string   `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Sort                 int32    `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChapterDto) Reset()         { *m = ChapterDto{} }
func (m *ChapterDto) String() string { return proto.CompactTextString(m) }
func (*ChapterDto) ProtoMessage()    {}
func (*ChapterDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{9}
}

func (m *ChapterDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterDto.Unmarshal(m, b)
}
func (m *ChapterDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterDto.Marshal(b, m, deterministic)
}
func (m *ChapterDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterDto.Merge(m, src)
}
func (m *ChapterDto) XXX_Size() int {
	return xxx_messageInfo_ChapterDto.Size(m)
}
func (m *ChapterDto) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterDto.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterDto proto.InternalMessageInfo

func (m *ChapterDto) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChapterDto) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

func (m *ChapterDto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChapterDto) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

type ChapterDtoList struct {
	Rows                 []*ChapterDto `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ChapterDtoList) Reset()         { *m = ChapterDtoList{} }
func (m *ChapterDtoList) String() string { return proto.CompactTextString(m) }
func (*ChapterDtoList) ProtoMessage()    {}
func (*ChapterDtoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{10}
}

func (m *ChapterDtoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterDtoList.Unmarshal(m, b)
}
func (m *ChapterDtoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterDtoList.Marshal(b, m, deterministic)
}
func (m *ChapterDtoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterDtoList.Merge(m, src)
}
func (m *ChapterDtoList) XXX_Size() int {
	return xxx_messageInfo_ChapterDtoList.Size(m)
}
func (m *ChapterDtoList) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterDtoList.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterDtoList proto.InternalMessageInfo

func (m *ChapterDtoList) GetRows() []*ChapterDto {
	if m != nil {
		return m.Rows
	}
	return nil
}

type ChapterPageDto struct {
	Page                 int64         `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64         `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sort                 []string      `protobuf:"bytes,3,rep,name=sort,proto3" json:"sort,omitempty"`
	Blurry               string        `protobuf:"bytes,4,opt,name=blurry,proto3" json:"blurry,omitempty"`
	Total                int64         `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	CreateTime           []string      `protobuf:"bytes,6,rep,name=createTime,proto3" json:"createTime,omitempty"`
	CourseId             string        `protobuf:"bytes,7,opt,name=courseId,proto3" json:"courseId,omitempty"`
	Rows                 []*ChapterDto `protobuf:"bytes,8,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ChapterPageDto) Reset()         { *m = ChapterPageDto{} }
func (m *ChapterPageDto) String() string { return proto.CompactTextString(m) }
func (*ChapterPageDto) ProtoMessage()    {}
func (*ChapterPageDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{11}
}

func (m *ChapterPageDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterPageDto.Unmarshal(m, b)
}
func (m *ChapterPageDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterPageDto.Marshal(b, m, deterministic)
}
func (m *ChapterPageDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterPageDto.Merge(m, src)
}
func (m *ChapterPageDto) XXX_Size() int {
	return xxx_messageInfo_ChapterPageDto.Size(m)
}
func (m *ChapterPageDto) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterPageDto.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterPageDto proto.InternalMessageInfo

func (m *ChapterPageDto) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ChapterPageDto) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ChapterPageDto) GetSort() []string {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *ChapterPageDto) GetBlurry() string {
	if m != nil {
		return m.Blurry
	}
	return ""
}

func (m *ChapterPageDto) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ChapterPageDto) GetCreateTime() []string {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *ChapterPageDto) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

func (m *ChapterPageDto) GetRows() []*ChapterDto {
	if m != nil {
		return m.Rows
	}
	return nil
}

//Section Dto
type SectionDto struct {
	//
	// id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//
	// 标题
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	//
	// 课程|course.id
	CourseId string `protobuf:"bytes,3,opt,name=courseId,proto3" json:"courseId,omitempty"`
	//
	// 大章|chapter.id
	ChapterId string `protobuf:"bytes,4,opt,name=chapterId,proto3" json:"chapterId,omitempty"`
	//
	// 视频
	Video string `protobuf:"bytes,5,opt,name=video,proto3" json:"video,omitempty"`
	//
	// 时长|单位秒
	Time int32 `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	//
	// 收费
	Charge string `protobuf:"bytes,7,opt,name=charge,proto3" json:"charge,omitempty"`
	//
	// 顺序
	Sort int32 `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`
	//
	// 创建时间
	CreatedTime string `protobuf:"bytes,9,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	//
	// 修改时间
	UpdatedTime          string   `protobuf:"bytes,10,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SectionDto) Reset()         { *m = SectionDto{} }
func (m *SectionDto) String() string { return proto.CompactTextString(m) }
func (*SectionDto) ProtoMessage()    {}
func (*SectionDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{12}
}

func (m *SectionDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SectionDto.Unmarshal(m, b)
}
func (m *SectionDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SectionDto.Marshal(b, m, deterministic)
}
func (m *SectionDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SectionDto.Merge(m, src)
}
func (m *SectionDto) XXX_Size() int {
	return xxx_messageInfo_SectionDto.Size(m)
}
func (m *SectionDto) XXX_DiscardUnknown() {
	xxx_messageInfo_SectionDto.DiscardUnknown(m)
}

var xxx_messageInfo_SectionDto proto.InternalMessageInfo

func (m *SectionDto) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SectionDto) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SectionDto) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

func (m *SectionDto) GetChapterId() string {
	if m != nil {
		return m.ChapterId
	}
	return ""
}

func (m *SectionDto) GetVideo() string {
	if m != nil {
		return m.Video
	}
	return ""
}

func (m *SectionDto) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *SectionDto) GetCharge() string {
	if m != nil {
		return m.Charge
	}
	return ""
}

func (m *SectionDto) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *SectionDto) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

func (m *SectionDto) GetUpdatedTime() string {
	if m != nil {
		return m.UpdatedTime
	}
	return ""
}

type SectionPageDto struct {
	Page                 int64         `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64         `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sort                 []string      `protobuf:"bytes,3,rep,name=sort,proto3" json:"sort,omitempty"`
	Blurry               string        `protobuf:"bytes,4,opt,name=blurry,proto3" json:"blurry,omitempty"`
	Total                int64         `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	CreateTime           []string      `protobuf:"bytes,6,rep,name=createTime,proto3" json:"createTime,omitempty"`
	CourseId             string        `protobuf:"bytes,7,opt,name=courseId,proto3" json:"courseId,omitempty"`
	ChapterId            string        `protobuf:"bytes,8,opt,name=chapterId,proto3" json:"chapterId,omitempty"`
	Rows                 []*SectionDto `protobuf:"bytes,9,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SectionPageDto) Reset()         { *m = SectionPageDto{} }
func (m *SectionPageDto) String() string { return proto.CompactTextString(m) }
func (*SectionPageDto) ProtoMessage()    {}
func (*SectionPageDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{13}
}

func (m *SectionPageDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SectionPageDto.Unmarshal(m, b)
}
func (m *SectionPageDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SectionPageDto.Marshal(b, m, deterministic)
}
func (m *SectionPageDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SectionPageDto.Merge(m, src)
}
func (m *SectionPageDto) XXX_Size() int {
	return xxx_messageInfo_SectionPageDto.Size(m)
}
func (m *SectionPageDto) XXX_DiscardUnknown() {
	xxx_messageInfo_SectionPageDto.DiscardUnknown(m)
}

var xxx_messageInfo_SectionPageDto proto.InternalMessageInfo

func (m *SectionPageDto) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SectionPageDto) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SectionPageDto) GetSort() []string {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *SectionPageDto) GetBlurry() string {
	if m != nil {
		return m.Blurry
	}
	return ""
}

func (m *SectionPageDto) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SectionPageDto) GetCreateTime() []string {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *SectionPageDto) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

func (m *SectionPageDto) GetChapterId() string {
	if m != nil {
		return m.ChapterId
	}
	return ""
}

func (m *SectionPageDto) GetRows() []*SectionDto {
	if m != nil {
		return m.Rows
	}
	return nil
}

//Teacher Dto
type TeacherDto struct {
	//
	// id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//
	// 姓名
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//
	// 头像
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	//
	// 职位
	Position string `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	//
	// 简介
	Intro                string   `protobuf:"bytes,5,opt,name=intro,proto3" json:"intro,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeacherDto) Reset()         { *m = TeacherDto{} }
func (m *TeacherDto) String() string { return proto.CompactTextString(m) }
func (*TeacherDto) ProtoMessage()    {}
func (*TeacherDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{14}
}

func (m *TeacherDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeacherDto.Unmarshal(m, b)
}
func (m *TeacherDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeacherDto.Marshal(b, m, deterministic)
}
func (m *TeacherDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeacherDto.Merge(m, src)
}
func (m *TeacherDto) XXX_Size() int {
	return xxx_messageInfo_TeacherDto.Size(m)
}
func (m *TeacherDto) XXX_DiscardUnknown() {
	xxx_messageInfo_TeacherDto.DiscardUnknown(m)
}

var xxx_messageInfo_TeacherDto proto.InternalMessageInfo

func (m *TeacherDto) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TeacherDto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TeacherDto) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *TeacherDto) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *TeacherDto) GetIntro() string {
	if m != nil {
		return m.Intro
	}
	return ""
}

type TeacherPageDto struct {
	Page                 int64         `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64         `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sort                 []string      `protobuf:"bytes,3,rep,name=sort,proto3" json:"sort,omitempty"`
	Blurry               string        `protobuf:"bytes,4,opt,name=blurry,proto3" json:"blurry,omitempty"`
	Total                int64         `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	Rows                 []*TeacherDto `protobuf:"bytes,6,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TeacherPageDto) Reset()         { *m = TeacherPageDto{} }
func (m *TeacherPageDto) String() string { return proto.CompactTextString(m) }
func (*TeacherPageDto) ProtoMessage()    {}
func (*TeacherPageDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{15}
}

func (m *TeacherPageDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeacherPageDto.Unmarshal(m, b)
}
func (m *TeacherPageDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeacherPageDto.Marshal(b, m, deterministic)
}
func (m *TeacherPageDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeacherPageDto.Merge(m, src)
}
func (m *TeacherPageDto) XXX_Size() int {
	return xxx_messageInfo_TeacherPageDto.Size(m)
}
func (m *TeacherPageDto) XXX_DiscardUnknown() {
	xxx_messageInfo_TeacherPageDto.DiscardUnknown(m)
}

var xxx_messageInfo_TeacherPageDto proto.InternalMessageInfo

func (m *TeacherPageDto) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *TeacherPageDto) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *TeacherPageDto) GetSort() []string {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *TeacherPageDto) GetBlurry() string {
	if m != nil {
		return m.Blurry
	}
	return ""
}

func (m *TeacherPageDto) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *TeacherPageDto) GetRows() []*TeacherDto {
	if m != nil {
		return m.Rows
	}
	return nil
}

type TeacherDtoList struct {
	Rows                 []*TeacherDto `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TeacherDtoList) Reset()         { *m = TeacherDtoList{} }
func (m *TeacherDtoList) String() string { return proto.CompactTextString(m) }
func (*TeacherDtoList) ProtoMessage()    {}
func (*TeacherDtoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{16}
}

func (m *TeacherDtoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeacherDtoList.Unmarshal(m, b)
}
func (m *TeacherDtoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeacherDtoList.Marshal(b, m, deterministic)
}
func (m *TeacherDtoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeacherDtoList.Merge(m, src)
}
func (m *TeacherDtoList) XXX_Size() int {
	return xxx_messageInfo_TeacherDtoList.Size(m)
}
func (m *TeacherDtoList) XXX_DiscardUnknown() {
	xxx_messageInfo_TeacherDtoList.DiscardUnknown(m)
}

var xxx_messageInfo_TeacherDtoList proto.InternalMessageInfo

func (m *TeacherDtoList) GetRows() []*TeacherDto {
	if m != nil {
		return m.Rows
	}
	return nil
}

//CourseFileDto
type CourseFileDto struct {
	//*
	// id
	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	//*
	// 课程id
	CourseId string `protobuf:"bytes,2,opt,name=CourseId,proto3" json:"CourseId,omitempty"`
	//*
	// 地址
	Url string `protobuf:"bytes,3,opt,name=Url,proto3" json:"Url,omitempty"`
	//*
	// 文件名
	Name string `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	//*
	// 大小|字节b
	Size                 int32    `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseFileDto) Reset()         { *m = CourseFileDto{} }
func (m *CourseFileDto) String() string { return proto.CompactTextString(m) }
func (*CourseFileDto) ProtoMessage()    {}
func (*CourseFileDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{17}
}

func (m *CourseFileDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseFileDto.Unmarshal(m, b)
}
func (m *CourseFileDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseFileDto.Marshal(b, m, deterministic)
}
func (m *CourseFileDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseFileDto.Merge(m, src)
}
func (m *CourseFileDto) XXX_Size() int {
	return xxx_messageInfo_CourseFileDto.Size(m)
}
func (m *CourseFileDto) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseFileDto.DiscardUnknown(m)
}

var xxx_messageInfo_CourseFileDto proto.InternalMessageInfo

func (m *CourseFileDto) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CourseFileDto) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

func (m *CourseFileDto) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CourseFileDto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CourseFileDto) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type CourseFileDtoList struct {
	Rows                 []*CourseFileDto `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CourseFileDtoList) Reset()         { *m = CourseFileDtoList{} }
func (m *CourseFileDtoList) String() string { return proto.CompactTextString(m) }
func (*CourseFileDtoList) ProtoMessage()    {}
func (*CourseFileDtoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{18}
}

func (m *CourseFileDtoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseFileDtoList.Unmarshal(m, b)
}
func (m *CourseFileDtoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseFileDtoList.Marshal(b, m, deterministic)
}
func (m *CourseFileDtoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseFileDtoList.Merge(m, src)
}
func (m *CourseFileDtoList) XXX_Size() int {
	return xxx_messageInfo_CourseFileDtoList.Size(m)
}
func (m *CourseFileDtoList) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseFileDtoList.DiscardUnknown(m)
}

var xxx_messageInfo_CourseFileDtoList proto.InternalMessageInfo

func (m *CourseFileDtoList) GetRows() []*CourseFileDto {
	if m != nil {
		return m.Rows
	}
	return nil
}

//修改排序使用
type SortDto struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	OldSort              int32    `protobuf:"varint,2,opt,name=OldSort,proto3" json:"OldSort,omitempty"`
	NewSort              int32    `protobuf:"varint,3,opt,name=NewSort,proto3" json:"NewSort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SortDto) Reset()         { *m = SortDto{} }
func (m *SortDto) String() string { return proto.CompactTextString(m) }
func (*SortDto) ProtoMessage()    {}
func (*SortDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{19}
}

func (m *SortDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SortDto.Unmarshal(m, b)
}
func (m *SortDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SortDto.Marshal(b, m, deterministic)
}
func (m *SortDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortDto.Merge(m, src)
}
func (m *SortDto) XXX_Size() int {
	return xxx_messageInfo_SortDto.Size(m)
}
func (m *SortDto) XXX_DiscardUnknown() {
	xxx_messageInfo_SortDto.DiscardUnknown(m)
}

var xxx_messageInfo_SortDto proto.InternalMessageInfo

func (m *SortDto) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SortDto) GetOldSort() int32 {
	if m != nil {
		return m.OldSort
	}
	return 0
}

func (m *SortDto) GetNewSort() int32 {
	if m != nil {
		return m.NewSort
	}
	return 0
}

type MemberCourseDto struct {
	MemberId             string   `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	CourseId             string   `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	LastLearn            string   `protobuf:"bytes,3,opt,name=last_learn,json=lastLearn,proto3" json:"last_learn,omitempty"`
	CreateAt             string   `protobuf:"bytes,4,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt             string   `protobuf:"bytes,5,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberCourseDto) Reset()         { *m = MemberCourseDto{} }
func (m *MemberCourseDto) String() string { return proto.CompactTextString(m) }
func (*MemberCourseDto) ProtoMessage()    {}
func (*MemberCourseDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_689623016e041112, []int{20}
}

func (m *MemberCourseDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberCourseDto.Unmarshal(m, b)
}
func (m *MemberCourseDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberCourseDto.Marshal(b, m, deterministic)
}
func (m *MemberCourseDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberCourseDto.Merge(m, src)
}
func (m *MemberCourseDto) XXX_Size() int {
	return xxx_messageInfo_MemberCourseDto.Size(m)
}
func (m *MemberCourseDto) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberCourseDto.DiscardUnknown(m)
}

var xxx_messageInfo_MemberCourseDto proto.InternalMessageInfo

func (m *MemberCourseDto) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *MemberCourseDto) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

func (m *MemberCourseDto) GetLastLearn() string {
	if m != nil {
		return m.LastLearn
	}
	return ""
}

func (m *MemberCourseDto) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *MemberCourseDto) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

func init() {
	proto.RegisterType((*CourseDto)(nil), "course.CourseDto")
	proto.RegisterType((*CoursePageDto)(nil), "course.CoursePageDto")
	proto.RegisterType((*CourseDtoList)(nil), "course.CourseDtoList")
	proto.RegisterType((*CourseContentDto)(nil), "course.CourseContentDto")
	proto.RegisterType((*CourseCategoryDto)(nil), "course.CourseCategoryDto")
	proto.RegisterType((*CourseCategoryDtoList)(nil), "course.CourseCategoryDtoList")
	proto.RegisterType((*CategoryDto)(nil), "course.CategoryDto")
	proto.RegisterType((*CategoryPageDto)(nil), "course.CategoryPageDto")
	proto.RegisterType((*CategoryDtoList)(nil), "course.CategoryDtoList")
	proto.RegisterType((*ChapterDto)(nil), "course.ChapterDto")
	proto.RegisterType((*ChapterDtoList)(nil), "course.ChapterDtoList")
	proto.RegisterType((*ChapterPageDto)(nil), "course.ChapterPageDto")
	proto.RegisterType((*SectionDto)(nil), "course.SectionDto")
	proto.RegisterType((*SectionPageDto)(nil), "course.SectionPageDto")
	proto.RegisterType((*TeacherDto)(nil), "course.TeacherDto")
	proto.RegisterType((*TeacherPageDto)(nil), "course.TeacherPageDto")
	proto.RegisterType((*TeacherDtoList)(nil), "course.TeacherDtoList")
	proto.RegisterType((*CourseFileDto)(nil), "course.CourseFileDto")
	proto.RegisterType((*CourseFileDtoList)(nil), "course.CourseFileDtoList")
	proto.RegisterType((*SortDto)(nil), "course.SortDto")
	proto.RegisterType((*MemberCourseDto)(nil), "course.MemberCourseDto")
}

func init() {
	proto.RegisterFile("gitee.com/jingshanccc/course/course/proto/dto/course.proto", fileDescriptor_689623016e041112)
}

var fileDescriptor_689623016e041112 = []byte{
	// 994 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0x5f, 0x6f, 0xdc, 0x44,
	0x10, 0x97, 0xe3, 0x8b, 0xcf, 0x9e, 0xd0, 0x6b, 0xe2, 0xd2, 0x68, 0x09, 0x7f, 0x74, 0xb2, 0x04,
	0x3d, 0x24, 0x9a, 0x48, 0x20, 0xa1, 0xaa, 0x42, 0x48, 0x21, 0x51, 0xa5, 0x93, 0xda, 0x82, 0x9c,
	0xf2, 0x82, 0x84, 0x82, 0x63, 0xaf, 0x2e, 0x46, 0xbe, 0xf3, 0x69, 0xbd, 0xd7, 0x12, 0x3e, 0x00,
	0xdf, 0x82, 0x17, 0xc4, 0xc7, 0xe0, 0x81, 0x4f, 0xc2, 0x27, 0xe1, 0x01, 0xcd, 0xcc, 0xee, 0xda,
	0xbe, 0x4b, 0x1b, 0xfa, 0x52, 0xc1, 0xd3, 0xed, 0xfc, 0x66, 0x66, 0x77, 0xe6, 0x37, 0xb3, 0x3b,
	0x3e, 0x78, 0x38, 0x2b, 0xb5, 0x94, 0x87, 0x79, 0x3d, 0x3f, 0xfa, 0xb1, 0x5c, 0xcc, 0x9a, 0xcb,
	0x6c, 0x91, 0xe7, 0xf9, 0x51, 0x5e, 0xaf, 0x54, 0x23, 0xed, 0xcf, 0x52, 0xd5, 0xba, 0x3e, 0x2a,
	0x74, 0x6d, 0x80, 0x43, 0x02, 0xe2, 0x80, 0xa5, 0xe4, 0xd7, 0x01, 0x44, 0x27, 0xb4, 0x3c, 0xd5,
	0x75, 0x3c, 0x82, 0xad, 0xb2, 0x10, 0xde, 0xd8, 0x9b, 0x44, 0xe9, 0x56, 0x59, 0xc4, 0x31, 0x0c,
	0x16, 0xd9, 0x5c, 0x8a, 0x2d, 0x42, 0x68, 0x1d, 0x0b, 0x18, 0x36, 0xab, 0xf9, 0x3c, 0x53, 0x57,
	0xc2, 0x27, 0xd8, 0x8a, 0x68, 0xad, 0xcb, 0xb9, 0x14, 0x83, 0xb1, 0x37, 0xd9, 0x4e, 0x69, 0x1d,
	0xbf, 0x0d, 0xdb, 0x4b, 0x55, 0xe6, 0x52, 0x6c, 0x8f, 0xbd, 0x89, 0x97, 0xb2, 0x80, 0x68, 0x39,
	0xcf, 0x66, 0x52, 0x04, 0xb4, 0x03, 0x0b, 0x88, 0x56, 0xf2, 0xb9, 0xac, 0xc4, 0x90, 0x51, 0x12,
	0xe2, 0x7d, 0x08, 0xf2, 0xcb, 0x4c, 0xcd, 0xa4, 0x08, 0x09, 0x36, 0x12, 0xe2, 0x8d, 0xce, 0xf4,
	0xaa, 0x11, 0x11, 0xe3, 0x2c, 0x21, 0x2e, 0x17, 0xaa, 0xae, 0x2a, 0x01, 0x14, 0x87, 0x91, 0x30,
	0xba, 0xa6, 0x56, 0x5a, 0xec, 0x70, 0x74, 0xb8, 0x8e, 0xdf, 0x83, 0x28, 0x57, 0x32, 0xd3, 0xb2,
	0x38, 0xd6, 0xe2, 0x2d, 0xda, 0xa6, 0x05, 0x50, 0xbb, 0x5a, 0x16, 0x46, 0x7b, 0x8b, 0xb5, 0x0e,
	0x88, 0x3f, 0x00, 0xc8, 0x33, 0x2d, 0x67, 0xb5, 0x2a, 0x65, 0x23, 0x46, 0x63, 0x7f, 0x12, 0xa5,
	0x1d, 0x24, 0x3e, 0x84, 0x30, 0xbf, 0xcc, 0x96, 0x5a, 0xaa, 0x46, 0xdc, 0x1e, 0xfb, 0x93, 0x9d,
	0x4f, 0xe3, 0x43, 0x53, 0x82, 0x13, 0xc6, 0x4f, 0x75, 0x9d, 0x3a, 0x1b, 0xb4, 0x6f, 0x64, 0xae,
	0xcb, 0x7a, 0xd1, 0x88, 0xdd, 0xbe, 0xfd, 0x19, 0xe3, 0x64, 0x6f, 0x6d, 0xb0, 0x0e, 0x79, 0xbd,
	0xd0, 0x72, 0xa1, 0xc5, 0x1e, 0xd7, 0xc1, 0x88, 0xf1, 0x27, 0x30, 0xd4, 0x32, 0xcb, 0x2f, 0xa5,
	0x12, 0xf1, 0xd8, 0xeb, 0x6e, 0xf4, 0x8c, 0x61, 0xdc, 0xc8, 0x9a, 0x60, 0x96, 0x66, 0x39, 0x2d,
	0xc4, 0x1d, 0xce, 0xd2, 0x01, 0xc9, 0x9f, 0x1e, 0xdc, 0xe2, 0xfe, 0xf8, 0x26, 0x9b, 0x51, 0x8f,
	0xc4, 0x30, 0x58, 0x62, 0xe9, 0xb0, 0x4b, 0xfc, 0x94, 0xd6, 0xc4, 0x6d, 0xf9, 0x33, 0xf7, 0x89,
	0x9f, 0xd2, 0xda, 0xf1, 0xed, 0x13, 0x33, 0xcc, 0xf7, 0x3e, 0x04, 0x17, 0xd5, 0x4a, 0xa9, 0x2b,
	0xea, 0x91, 0x28, 0x35, 0x12, 0x56, 0x5e, 0xd7, 0x3a, 0xab, 0xa8, 0x4b, 0xfc, 0x94, 0x05, 0x62,
	0x98, 0x8a, 0xf1, 0x0c, 0xbb, 0x2a, 0x30, 0x0c, 0x3b, 0x24, 0xfe, 0x10, 0x06, 0xaa, 0x7e, 0xd1,
	0x88, 0x21, 0xb1, 0xb5, 0xe7, 0xd8, 0xb5, 0xed, 0x9c, 0x92, 0x3a, 0xf9, 0xdc, 0x66, 0x70, 0xaa,
	0xeb, 0xc7, 0x65, 0xa3, 0x9d, 0x9f, 0xf7, 0x6a, 0xbf, 0x2f, 0x60, 0x97, 0xa1, 0x13, 0xe6, 0xd5,
	0x5c, 0x90, 0xa9, 0xbb, 0x20, 0xd3, 0x02, 0x8b, 0x60, 0xb4, 0xe6, 0x8e, 0x58, 0x31, 0x39, 0x87,
	0x3d, 0xe3, 0xcd, 0x2d, 0x71, 0x75, 0x9d, 0xfb, 0x01, 0x84, 0x6c, 0x34, 0x2d, 0x8c, 0xbf, 0x93,
	0x31, 0x7b, 0xeb, 0x3a, 0x2d, 0xcc, 0x55, 0xeb, 0x20, 0xc9, 0x23, 0xb8, 0xbb, 0x71, 0x00, 0xa5,
	0x77, 0xbf, 0x97, 0xde, 0x3b, 0xfd, 0xf4, 0x3a, 0xc6, 0x26, 0xcd, 0xef, 0x61, 0x67, 0x2d, 0xc4,
	0x1b, 0x9f, 0x80, 0x7d, 0x08, 0x96, 0x99, 0xc2, 0xa4, 0x39, 0x2c, 0x23, 0xb9, 0x92, 0x0f, 0xda,
	0x2b, 0x96, 0xfc, 0xe1, 0xc1, 0x6d, 0xbb, 0xff, 0x9b, 0x6f, 0xa1, 0x36, 0xd2, 0xa0, 0x17, 0xe9,
	0xbd, 0x5e, 0xeb, 0xdc, 0x71, 0x1c, 0x6d, 0xb0, 0xf3, 0xb0, 0x8d, 0xde, 0xf2, 0x7b, 0xaf, 0xc7,
	0xef, 0x2b, 0x7c, 0x7f, 0x00, 0x68, 0x6f, 0xfa, 0x06, 0xb1, 0x07, 0x10, 0xe6, 0x6b, 0xb5, 0xb7,
	0xb2, 0x23, 0xdd, 0xef, 0x90, 0x7e, 0x1d, 0xb9, 0x0f, 0x60, 0xd4, 0x9e, 0x40, 0xc1, 0x7d, 0xd4,
	0x0b, 0xee, 0xba, 0x17, 0x87, 0x63, 0xfb, 0xcb, 0x73, 0xae, 0xff, 0xbd, 0x8b, 0xdd, 0xa5, 0x66,
	0xb8, 0x46, 0x8d, 0x4d, 0x30, 0xbc, 0x21, 0xc1, 0x5f, 0xb6, 0x00, 0xda, 0x77, 0x73, 0x83, 0x7d,
	0x0c, 0xac, 0xd4, 0x95, 0xed, 0x6b, 0x16, 0x7a, 0x07, 0xfb, 0x6b, 0x07, 0xe3, 0xac, 0xe0, 0x43,
	0xa6, 0x85, 0xc9, 0xb2, 0x05, 0x70, 0xbf, 0xe7, 0x65, 0x21, 0x6b, 0x4a, 0x34, 0x4a, 0x59, 0x70,
	0x13, 0x31, 0xe8, 0x4c, 0xc4, 0x76, 0x9e, 0x0d, 0x7b, 0xf3, 0xcc, 0xd2, 0x1a, 0x76, 0xe6, 0xd3,
	0x18, 0x76, 0xcc, 0x38, 0x22, 0xa6, 0x78, 0xd0, 0x75, 0x21, 0xb4, 0x30, 0x23, 0x89, 0x2c, 0x80,
	0x2d, 0x3a, 0x50, 0xf2, 0xb7, 0x07, 0x23, 0x43, 0xc4, 0xff, 0xab, 0xd2, 0x3d, 0xc2, 0xc3, 0x75,
	0xc2, 0x6d, 0x1f, 0x44, 0x2f, 0x1d, 0x95, 0xdc, 0x07, 0x3f, 0x01, 0xb4, 0x53, 0xef, 0x5f, 0xbd,
	0x6e, 0xee, 0xe3, 0xc4, 0xef, 0x7e, 0x9c, 0x1c, 0x40, 0xb8, 0xac, 0x9b, 0x12, 0x37, 0x37, 0x99,
	0x3b, 0x99, 0x3c, 0x16, 0x5a, 0xb9, 0xe2, 0x93, 0x90, 0xfc, 0xe6, 0xc1, 0xc8, 0x1c, 0xfd, 0xe6,
	0x89, 0xb7, 0xf4, 0x04, 0x7d, 0x7a, 0x3a, 0x1f, 0x00, 0x4c, 0xcf, 0x03, 0x17, 0xe3, 0x0d, 0x2f,
	0xc8, 0x86, 0xe7, 0xca, 0x8e, 0xd5, 0x47, 0x65, 0x25, 0x5f, 0x77, 0xb8, 0xed, 0x82, 0xff, 0xad,
	0xaa, 0x0c, 0xc3, 0xb8, 0xc4, 0x94, 0x9f, 0x66, 0xe6, 0xe3, 0x31, 0x4a, 0x69, 0x8d, 0xd8, 0x19,
	0x52, 0xb3, 0xcd, 0x57, 0x02, 0xd7, 0xc9, 0x97, 0x76, 0xae, 0x9a, 0x63, 0x29, 0xe6, 0x8f, 0x7b,
	0x31, 0xdf, 0xed, 0x8f, 0x3c, 0x63, 0x68, 0xc2, 0x7e, 0x02, 0xc3, 0xb3, 0x5a, 0xbd, 0x6c, 0x98,
	0x7f, 0x5d, 0x15, 0xa8, 0xa5, 0x78, 0xb7, 0x53, 0x2b, 0xa2, 0xe6, 0xa9, 0x7c, 0x71, 0xc6, 0x25,
	0x21, 0x8d, 0x11, 0x93, 0xdf, 0x3d, 0xb8, 0xfd, 0x44, 0xce, 0x2f, 0xa4, 0x6a, 0xbf, 0xa2, 0xdf,
	0x85, 0x68, 0x4e, 0xd0, 0xb9, 0xeb, 0xb5, 0x90, 0x81, 0x69, 0x81, 0x4a, 0x8e, 0x0e, 0x95, 0xeb,
	0xef, 0xfe, 0xfb, 0x00, 0x55, 0xd6, 0xe8, 0xf3, 0x4a, 0x66, 0x6a, 0x61, 0xd8, 0x89, 0x10, 0x79,
	0x8c, 0x00, 0xf9, 0xd2, 0xdd, 0x39, 0xcf, 0xb4, 0x6d, 0x42, 0x06, 0x8e, 0x35, 0x2a, 0xf9, 0xda,
	0xa3, 0x92, 0x1b, 0x31, 0x64, 0xe0, 0x58, 0x7f, 0x75, 0xf4, 0xdd, 0xfd, 0xd7, 0xfa, 0xb3, 0x70,
	0x11, 0xd0, 0xf2, 0xb3, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x74, 0xb0, 0xd8, 0x64, 0x0c,
	0x00, 0x00,
}
